import { useState } from 'react';
import { MessageSquareText } from 'lucide-react';
import { scanService } from '../services/scanService';
import Button from './ui/Button';
import { Alert } from './ui/States';
import { useToast } from './ui/toastContext';

/**
 * Evidence-based "why" for a candidate. The optional AI text only rephrases this evidence; it is labelled
 * as such and never changes the verdict.
 */
function ExplanationPanel({ scanId, run, aiAvailable }) {
  const notify = useToast();
  const [ai, setAi] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const { explanation } = run;

  const requestAi = async () => {
    setLoading(true);
    setError('');
    try {
      setAi(await scanService.requestAiExplanation(scanId, run.candidate_id));
      notify({ tone: 'success', title: 'Summary ready', message: 'Written by a language model from the evidence; the verdict is unchanged.' });
    } catch (err) {
      setError(err.message);
      notify({ tone: 'danger', title: 'Summary could not be written', message: err.message });
    } finally {
      setLoading(false);
    }
  };

  const disabledReason = !run.candidate_code
    ? 'There is no candidate code to explain.'
    : !aiAvailable
      ? 'Needs a language model: start Ollama or set an OpenRouter key on the server.'
      : '';

  return (
    <div className="explanation">
      <p className="explanation-headline">{explanation.headline}</p>

      {explanation.limitations.length ? (
        <Alert tone="warning" title="Limitations">
          <ul className="bullet-list">
            {explanation.limitations.map((limitation) => (
              <li key={limitation}>{limitation}</li>
            ))}
          </ul>
        </Alert>
      ) : null}

      {explanation.sections.map((section) => (
        <section key={section.title} className="explanation-section">
          <h4>{section.title}</h4>
          <ul className="bullet-list">
            {section.points.map((point, index) => (
              <li key={index}>{point}</li>
            ))}
          </ul>
        </section>
      ))}

      <div className="ai-explanation">
        {ai ? (
          <>
            <p className="ai-label">
              <MessageSquareText size={14} aria-hidden="true" /> Plain-language summary · <span className="mono">{ai.model}</span>
            </p>
            <p className="ai-text">{ai.text}</p>
            <p className="ai-disclaimer">{ai.disclaimer}</p>
          </>
        ) : (
          <div className="ai-request">
            <Button size="sm" icon={MessageSquareText} onClick={requestAi} loading={loading} disabled={Boolean(disabledReason)}>
              {loading ? 'Writing summary…' : 'Summarise in plain language'}
            </Button>
            <p className="muted small">{disabledReason || 'Generated by a language model from the evidence above. It does not affect the verdict.'}</p>
          </div>
        )}
        {error ? (
          <Alert tone="danger" title="Summary could not be written" className="ai-error">
            {error}
          </Alert>
        ) : null}
      </div>
    </div>
  );
}

export default ExplanationPanel;
